// <auto-generated />
using System;
using Day29IdentityFramework.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Day29IdentityFramework.Migrations
{
    [DbContext(typeof(IdentityFrameworkTestDbContext))]
    [Migration("20191121180411_initialPresidentmigration")]
    partial class initialPresidentmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Day29IdentityFramework.Models.Presidents", b =>
                {
                    b.Property<int>("PresidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("InaugurationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("Terms")
                        .HasColumnType("int");

                    b.HasKey("PresidentId");

                    b.ToTable("Presidents");

                    b.HasData(
                        new
                        {
                            PresidentId = 44,
                            InaugurationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Barak Obama",
                            Terms = 2
                        },
                        new
                        {
                            PresidentId = 22,
                            InaugurationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Grover Cleveland",
                            Terms = 1
                        },
                        new
                        {
                            PresidentId = 24,
                            InaugurationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Grover Cleveland",
                            Terms = 1
                        },
                        new
                        {
                            PresidentId = 38,
                            InaugurationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gerald Ford",
                            Terms = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
